import {
  Challenge,
  ChallengeCategory,
  ChallengeDetails,
  ChallengeMetadata,
} from '@/lib/types';

export const MOCK_CHALLENGES_DETAILS: ChallengeDetails[] = [
  {
    id: '1',
    name: 'Buffer Overflow',
    tags: ['pwn'],
    points: 100,
    difficulty: 'hard',
    solvesNumber: 5,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'This challenge involves exploiting a classic buffer overflow vulnerability in a C program. Your goal is to overflow the buffer and gain control of the program execution.',
    hints: ['Check the stack alignment', 'Try different buffer sizes'],
    createdAt: new Date('2024-01-15'),
    category: 'static',
    assets: ['buffer_overflow.c', 'vuln_binary'],
    additionalLinks: [
      'https://exploit-db.com/docs/english/28475-linux-stack-based-buffer-overflows.pdf',
    ],
    ports: [4444],
    dynamicFlag: false,
    flag: 'flag{buffer_overflow_master}',
    solves: [
      {
        id: 1,
        username: 'hacker1',
        solvedAt: new Date('2024-01-16'),
        flag: 'flag{buffer_overflow_master}',
        correct: true,
      },
      {
        id: 2,
        username: 'pwn_master',
        solvedAt: new Date('2024-01-17'),
        flag: 'flag{buffer_overflow_master}',
        correct: true,
      },
      {
        id: 3,
        username: 'ctf_newbie',
        solvedAt: new Date('2024-01-18'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 4,
        username: 'binary_explorer',
        solvedAt: new Date('2024-01-19'),
        flag: 'flag{buffer_overflow_master}',
        correct: true,
      },
      {
        id: 5,
        username: 'security_researcher',
        solvedAt: new Date('2024-01-20'),
        flag: 'flag{buffer_overflow_master}',
        correct: true,
      },
      {
        id: 6,
        username: 'code_breaker',
        solvedAt: new Date('2024-01-21'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 7,
        username: 'stack_smasher',
        solvedAt: new Date('2024-01-22'),
        flag: 'flag{buffer_overflow_master}',
        correct: true,
      },
      {
        id: 8,
        username: 'vuln_hunter',
        solvedAt: new Date('2024-01-23'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 9,
        username: 'exploit_dev',
        solvedAt: new Date('2024-01-24'),
        flag: 'flag{buffer_overflow_master}',
        correct: true,
      },
      {
        id: 10,
        username: 'pwn_champion',
        solvedAt: new Date('2024-01-25'),
        flag: 'flag{buffer_overflow_master}',
        correct: true,
      },
    ],
  },
  {
    id: '2',
    name: 'SQL Injection',
    tags: ['web'],
    points: 50,
    difficulty: 'medium',
    solvesNumber: 20,
    solveStatus: 'solved',
    deployedStatus: 'deployed',
    description:
      'This web challenge contains a login form vulnerable to SQL injection. Bypass the authentication to find the flag.',
    hints: [
      'Try using single quotes in the username field',
      'UNION SELECT might be useful',
    ],
    createdAt: new Date('2024-02-10'),
    category: 'bare' as ChallengeCategory,
    assets: ['login_form.php'],
    additionalLinks: [],
    ports: [8080],
    dynamicFlag: true,
    flag: 'flag{sql_injection_king}',
    solves: [
      {
        id: 11,
        username: 'webmaster',
        solvedAt: new Date('2024-02-11'),
        flag: 'flag{sql_injection_king}',
        correct: true,
      },
      {
        id: 12,
        username: 'sql_ninja',
        solvedAt: new Date('2024-02-12'),
        flag: 'flag{sql_injection_king}',
        correct: true,
      },
      {
        id: 13,
        username: 'web_hacker',
        solvedAt: new Date('2024-02-13'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 14,
        username: 'db_explorer',
        solvedAt: new Date('2024-02-14'),
        flag: 'flag{sql_injection_king}',
        correct: true,
      },
      {
        id: 15,
        username: 'injection_master',
        solvedAt: new Date('2024-02-15'),
        flag: 'flag{sql_injection_king}',
        correct: true,
      },
      {
        id: 16,
        username: 'web_security',
        solvedAt: new Date('2024-02-16'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 17,
        username: 'sql_hunter',
        solvedAt: new Date('2024-02-17'),
        flag: 'flag{sql_injection_king}',
        correct: true,
      },
      {
        id: 18,
        username: 'web_explorer',
        solvedAt: new Date('2024-02-18'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 19,
        username: 'injection_ninja',
        solvedAt: new Date('2024-02-19'),
        flag: 'flag{sql_injection_king}',
        correct: true,
      },
      {
        id: 20,
        username: 'sql_master',
        solvedAt: new Date('2024-02-20'),
        flag: 'flag{sql_injection_king}',
        correct: true,
      },
    ],
  },
  {
    id: '3',
    name: 'Reverse Engineering',
    tags: ['rev'],
    points: 75,
    difficulty: 'medium',
    solvesNumber: 12,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'Analyze this binary file to understand its behavior and extract the hidden flag. The flag is encrypted but the decryption routine is within the binary.',
    hints: ['Look for XOR operations', 'Check string comparisons'],
    createdAt: new Date('2024-03-05'),
    category: 'bare',
    assets: ['mystery_binary.exe', 'readme.txt'],
    additionalLinks: [],
    ports: [],
    dynamicFlag: false,
    flag: 'flag{reverse_engineering_pro}',
    solves: [
      {
        id: 21,
        username: 'rev_master',
        solvedAt: new Date('2024-03-06'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 22,
        username: 'binary_analyzer',
        solvedAt: new Date('2024-03-07'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 23,
        username: 'disassembler',
        solvedAt: new Date('2024-03-08'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 24,
        username: 'rev_ninja',
        solvedAt: new Date('2024-03-09'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 25,
        username: 'binary_hunter',
        solvedAt: new Date('2024-03-10'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 26,
        username: 'rev_explorer',
        solvedAt: new Date('2024-03-11'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 27,
        username: 'binary_master',
        solvedAt: new Date('2024-03-12'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 28,
        username: 'rev_hunter',
        solvedAt: new Date('2024-03-13'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 29,
        username: 'binary_ninja',
        solvedAt: new Date('2024-03-14'),
        flag: 'wrong_flag_here',
        correct: false,
      },
      {
        id: 30,
        username: 'rev_analyzer',
        solvedAt: new Date('2024-03-15'),
        flag: 'wrong_flag_here',
        correct: false,
      },
    ],
  },
];

export const MOCK_CHALLENGES: Challenge[] = MOCK_CHALLENGES_DETAILS.map(
  ({
    id,
    name,
    tags,
    points,
    difficulty,
    solvesNumber,
    solveStatus,
    deployedStatus,
    description,
    hints,
    createdAt,
    category,
    assets,
    additionalLinks,
    ports,
  }) => ({
    id,
    name,
    tags,
    points,
    difficulty,
    solvesNumber,
    solveStatus,
    deployedStatus,
    description,
    hints,
    createdAt,
    category,
    assets,
    additionalLinks,
    ports,
  })
);

export const MOCK_CHALLENGES_METADATA: ChallengeMetadata[] =
  MOCK_CHALLENGES_DETAILS.map(
    ({
      id,
      name,
      tags,
      points,
      difficulty,
      solvesNumber,
      solveStatus,
      deployedStatus,
    }) => ({
      id,
      name,
      tags,
      points,
      difficulty,
      solvesNumber,
      solveStatus,
      deployedStatus,
    })
  );
