import { Challenge, ChallengeCategory, ChallengeMetadata } from '@/lib/types';

export const MOCK_CHALLENGES = [
  {
    id: '1',
    name: 'Buffer Overflow',
    tags: ['pwn'],
    points: 100,
    difficulty: 'hard',
    solvesNumber: 5,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'This challenge involves exploiting a classic buffer overflow vulnerability in a C program. Your goal is to overflow the buffer and gain control of the program execution.',
    hints: ['Check the stack alignment', 'Try different buffer sizes'],
    createdAt: new Date('2024-01-15'),
    category: 'pwn' as ChallengeCategory,
    assets: ['buffer_overflow.c', 'vuln_binary'],
    additionalLinks: [
      'https://exploit-db.com/docs/english/28475-linux-stack-based-buffer-overflows.pdf',
    ],
    ports: [4444],
    dynamic: false,
  },
  {
    id: '2',
    name: 'SQL Injection',
    tags: ['web'],
    points: 50,
    difficulty: 'medium',
    solvesNumber: 20,
    solveStatus: 'solved',
    deployedStatus: 'deployed',
    description:
      'This web challenge contains a login form vulnerable to SQL injection. Bypass the authentication to find the flag.',
    hints: [
      'Try using single quotes in the username field',
      'UNION SELECT might be useful',
    ],
    createdAt: new Date('2024-02-10'),
    category: 'web' as ChallengeCategory,
    assets: ['login_form.php'],
    additionalLinks: [],
    ports: [8080],
    dynamic: true,
  },
  {
    id: '3',
    name: 'Reverse Engineering',
    tags: ['rev', 'binary'],
    points: 75,
    difficulty: 'medium',
    solvesNumber: 12,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'Analyze this binary file to understand its behavior and extract the hidden flag. The flag is encrypted but the decryption routine is within the binary.',
    hints: ['Look for XOR operations', 'Check string comparisons'],
    createdAt: new Date('2024-03-05'),
    category: 'rev' as ChallengeCategory,
    assets: ['mystery_binary.exe', 'readme.txt'],
    additionalLinks: [],
    ports: [],
    dynamic: false,
  },
  {
    id: '1',
    name: 'Buffer Overflow',
    tags: ['pwn'],
    points: 100,
    difficulty: 'hard',
    solvesNumber: 5,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'This challenge involves exploiting a classic buffer overflow vulnerability in a C program. Your goal is to overflow the buffer and gain control of the program execution.',
    hints: ['Check the stack alignment', 'Try different buffer sizes'],
    createdAt: new Date('2024-01-15'),
    category: 'pwn' as ChallengeCategory,
    assets: ['buffer_overflow.c', 'vuln_binary'],
    additionalLinks: [
      'https://exploit-db.com/docs/english/28475-linux-stack-based-buffer-overflows.pdf',
    ],
    ports: [4444],
    dynamic: false,
  },
  {
    id: '2',
    name: 'SQL Injection',
    tags: ['web'],
    points: 50,
    difficulty: 'medium',
    solvesNumber: 20,
    solveStatus: 'solved',
    deployedStatus: 'deployed',
    description:
      'This web challenge contains a login form vulnerable to SQL injection. Bypass the authentication to find the flag.',
    hints: [
      'Try using single quotes in the username field',
      'UNION SELECT might be useful',
    ],
    createdAt: new Date('2024-02-10'),
    category: 'web' as ChallengeCategory,
    assets: ['login_form.php'],
    additionalLinks: [],
    ports: [8080],
    dynamic: true,
  },
  {
    id: '3',
    name: 'Reverse Engineering',
    tags: ['rev', 'binary'],
    points: 75,
    difficulty: 'medium',
    solvesNumber: 12,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'Analyze this binary file to understand its behavior and extract the hidden flag. The flag is encrypted but the decryption routine is within the binary.',
    hints: ['Look for XOR operations', 'Check string comparisons'],
    createdAt: new Date('2024-03-05'),
    category: 'rev' as ChallengeCategory,
    assets: ['mystery_binary.exe', 'readme.txt'],
    additionalLinks: [],
    ports: [],
    dynamic: false,
  },
  {
    id: '4',
    name: 'Buffer Overflow',
    tags: ['pwn'],
    points: 100,
    difficulty: 'hard',
    solvesNumber: 5,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'This challenge involves exploiting a classic buffer overflow vulnerability in a C program. Your goal is to overflow the buffer and gain control of the program execution.',
    hints: ['Check the stack alignment', 'Try different buffer sizes'],
    createdAt: new Date('2024-01-15'),
    category: 'pwn' as ChallengeCategory,
    assets: ['buffer_overflow.c', 'vuln_binary'],
    additionalLinks: [
      'https://exploit-db.com/docs/english/28475-linux-stack-based-buffer-overflows.pdf',
    ],
    ports: [4444],
    dynamic: false,
  },
  {
    id: '5',
    name: 'SQL Injection',
    tags: ['web'],
    points: 50,
    difficulty: 'medium',
    solvesNumber: 20,
    solveStatus: 'solved',
    deployedStatus: 'deployed',
    description:
      'This web challenge contains a login form vulnerable to SQL injection. Bypass the authentication to find the flag.',
    hints: [
      'Try using single quotes in the username field',
      'UNION SELECT might be useful',
    ],
    createdAt: new Date('2024-02-10'),
    category: 'web' as ChallengeCategory,
    assets: ['login_form.php'],
    additionalLinks: [],
    ports: [8080],
    dynamic: true,
  },
  {
    id: '6',
    name: 'Reverse Engineering',
    tags: ['rev', 'binary'],
    points: 75,
    difficulty: 'medium',
    solvesNumber: 12,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'Analyze this binary file to understand its behavior and extract the hidden flag. The flag is encrypted but the decryption routine is within the binary.',
    hints: ['Look for XOR operations', 'Check string comparisons'],
    createdAt: new Date('2024-03-05'),
    category: 'rev' as ChallengeCategory,
    assets: ['mystery_binary.exe', 'readme.txt'],
    additionalLinks: [],
    ports: [],
    dynamic: false,
  },
  {
    id: '4',
    name: 'Buffer Overflow',
    tags: ['pwn'],
    points: 100,
    difficulty: 'hard',
    solvesNumber: 5,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'This challenge involves exploiting a classic buffer overflow vulnerability in a C program. Your goal is to overflow the buffer and gain control of the program execution.',
    hints: ['Check the stack alignment', 'Try different buffer sizes'],
    createdAt: new Date('2024-01-15'),
    category: 'pwn' as ChallengeCategory,
    assets: ['buffer_overflow.c', 'vuln_binary'],
    additionalLinks: [
      'https://exploit-db.com/docs/english/28475-linux-stack-based-buffer-overflows.pdf',
    ],
    ports: [4444],
    dynamic: false,
  },
  {
    id: '5',
    name: 'SQL Injection',
    tags: ['web'],
    points: 50,
    difficulty: 'medium',
    solvesNumber: 20,
    solveStatus: 'solved',
    deployedStatus: 'deployed',
    description:
      'This web challenge contains a login form vulnerable to SQL injection. Bypass the authentication to find the flag.',
    hints: [
      'Try using single quotes in the username field',
      'UNION SELECT might be useful',
    ],
    createdAt: new Date('2024-02-10'),
    category: 'web' as ChallengeCategory,
    assets: ['login_form.php'],
    additionalLinks: [],
    ports: [8080],
    dynamic: true,
  },
  {
    id: '6',
    name: 'Reverse Engineering',
    tags: ['rev', 'binary'],
    points: 75,
    difficulty: 'medium',
    solvesNumber: 12,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'Analyze this binary file to understand its behavior and extract the hidden flag. The flag is encrypted but the decryption routine is within the binary.',
    hints: ['Look for XOR operations', 'Check string comparisons'],
    createdAt: new Date('2024-03-05'),
    category: 'rev' as ChallengeCategory,
    assets: ['mystery_binary.exe', 'readme.txt'],
    additionalLinks: [],
    ports: [],
    dynamic: false,
  },
  {
    id: '4',
    name: 'Buffer Overflow',
    tags: ['pwn'],
    points: 100,
    difficulty: 'hard',
    solvesNumber: 5,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'This challenge involves exploiting a classic buffer overflow vulnerability in a C program. Your goal is to overflow the buffer and gain control of the program execution.',
    hints: ['Check the stack alignment', 'Try different buffer sizes'],
    createdAt: new Date('2024-01-15'),
    category: 'pwn' as ChallengeCategory,
    assets: ['buffer_overflow.c', 'vuln_binary'],
    additionalLinks: [
      'https://exploit-db.com/docs/english/28475-linux-stack-based-buffer-overflows.pdf',
    ],
    ports: [4444],
    dynamic: false,
  },
  {
    id: '5',
    name: 'SQL Injection',
    tags: ['web'],
    points: 50,
    difficulty: 'medium',
    solvesNumber: 20,
    solveStatus: 'solved',
    deployedStatus: 'deployed',
    description:
      'This web challenge contains a login form vulnerable to SQL injection. Bypass the authentication to find the flag.',
    hints: [
      'Try using single quotes in the username field',
      'UNION SELECT might be useful',
    ],
    createdAt: new Date('2024-02-10'),
    category: 'web' as ChallengeCategory,
    assets: ['login_form.php'],
    additionalLinks: [],
    ports: [8080],
    dynamic: true,
  },
  {
    id: '6',
    name: 'Reverse Engineering',
    tags: ['rev', 'binary'],
    points: 75,
    difficulty: 'medium',
    solvesNumber: 12,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'Analyze this binary file to understand its behavior and extract the hidden flag. The flag is encrypted but the decryption routine is within the binary.',
    hints: ['Look for XOR operations', 'Check string comparisons'],
    createdAt: new Date('2024-03-05'),
    category: 'rev' as ChallengeCategory,
    assets: ['mystery_binary.exe', 'readme.txt'],
    additionalLinks: [],
    ports: [],
    dynamic: false,
  },
  {
    id: '4',
    name: 'Buffer Overflow',
    tags: ['pwn'],
    points: 100,
    difficulty: 'hard',
    solvesNumber: 5,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'This challenge involves exploiting a classic buffer overflow vulnerability in a C program. Your goal is to overflow the buffer and gain control of the program execution.',
    hints: ['Check the stack alignment', 'Try different buffer sizes'],
    createdAt: new Date('2024-01-15'),
    category: 'pwn' as ChallengeCategory,
    assets: ['buffer_overflow.c', 'vuln_binary'],
    additionalLinks: [
      'https://exploit-db.com/docs/english/28475-linux-stack-based-buffer-overflows.pdf',
    ],
    ports: [4444],
    dynamic: false,
  },
  {
    id: '5',
    name: 'SQL Injection',
    tags: ['web'],
    points: 50,
    difficulty: 'medium',
    solvesNumber: 20,
    solveStatus: 'solved',
    deployedStatus: 'deployed',
    description:
      'This web challenge contains a login form vulnerable to SQL injection. Bypass the authentication to find the flag.',
    hints: [
      'Try using single quotes in the username field',
      'UNION SELECT might be useful',
    ],
    createdAt: new Date('2024-02-10'),
    category: 'web' as ChallengeCategory,
    assets: ['login_form.php'],
    additionalLinks: [],
    ports: [8080],
    dynamic: true,
  },
  {
    id: '6',
    name: 'Reverse Engineering',
    tags: ['rev', 'binary'],
    points: 75,
    difficulty: 'medium',
    solvesNumber: 12,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'Analyze this binary file to understand its behavior and extract the hidden flag. The flag is encrypted but the decryption routine is within the binary.',
    hints: ['Look for XOR operations', 'Check string comparisons'],
    createdAt: new Date('2024-03-05'),
    category: 'rev' as ChallengeCategory,
    assets: ['mystery_binary.exe', 'readme.txt'],
    additionalLinks: [],
    ports: [],
    dynamic: false,
  },
  {
    id: '4',
    name: 'Buffer Overflow',
    tags: ['pwn'],
    points: 100,
    difficulty: 'hard',
    solvesNumber: 5,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'This challenge involves exploiting a classic buffer overflow vulnerability in a C program. Your goal is to overflow the buffer and gain control of the program execution.',
    hints: ['Check the stack alignment', 'Try different buffer sizes'],
    createdAt: new Date('2024-01-15'),
    category: 'pwn' as ChallengeCategory,
    assets: ['buffer_overflow.c', 'vuln_binary'],
    additionalLinks: [
      'https://exploit-db.com/docs/english/28475-linux-stack-based-buffer-overflows.pdf',
    ],
    ports: [4444],
    dynamic: false,
  },
  {
    id: '5',
    name: 'SQL Injection',
    tags: ['web'],
    points: 50,
    difficulty: 'medium',
    solvesNumber: 20,
    solveStatus: 'solved',
    deployedStatus: 'deployed',
    description:
      'This web challenge contains a login form vulnerable to SQL injection. Bypass the authentication to find the flag.',
    hints: [
      'Try using single quotes in the username field',
      'UNION SELECT might be useful',
    ],
    createdAt: new Date('2024-02-10'),
    category: 'web' as ChallengeCategory,
    assets: ['login_form.php'],
    additionalLinks: [],
    ports: [8080],
    dynamic: true,
  },
  {
    id: '6',
    name: 'Reverse Engineering',
    tags: ['rev', 'binary'],
    points: 75,
    difficulty: 'medium',
    solvesNumber: 12,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'Analyze this binary file to understand its behavior and extract the hidden flag. The flag is encrypted but the decryption routine is within the binary.',
    hints: ['Look for XOR operations', 'Check string comparisons'],
    createdAt: new Date('2024-03-05'),
    category: 'rev' as ChallengeCategory,
    assets: ['mystery_binary.exe', 'readme.txt'],
    additionalLinks: [],
    ports: [],
    dynamic: false,
  },
  {
    id: '4',
    name: 'Buffer Overflow',
    tags: ['pwn'],
    points: 100,
    difficulty: 'hard',
    solvesNumber: 5,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'This challenge involves exploiting a classic buffer overflow vulnerability in a C program. Your goal is to overflow the buffer and gain control of the program execution.',
    hints: ['Check the stack alignment', 'Try different buffer sizes'],
    createdAt: new Date('2024-01-15'),
    category: 'pwn' as ChallengeCategory,
    assets: ['buffer_overflow.c', 'vuln_binary'],
    additionalLinks: [
      'https://exploit-db.com/docs/english/28475-linux-stack-based-buffer-overflows.pdf',
    ],
    ports: [4444],
    dynamic: false,
  },
  {
    id: '5',
    name: 'SQL Injection',
    tags: ['web'],
    points: 50,
    difficulty: 'medium',
    solvesNumber: 20,
    solveStatus: 'solved',
    deployedStatus: 'deployed',
    description:
      'This web challenge contains a login form vulnerable to SQL injection. Bypass the authentication to find the flag.',
    hints: [
      'Try using single quotes in the username field',
      'UNION SELECT might be useful',
    ],
    createdAt: new Date('2024-02-10'),
    category: 'web' as ChallengeCategory,
    assets: ['login_form.php'],
    additionalLinks: [],
    ports: [8080],
    dynamic: true,
  },
  {
    id: '6',
    name: 'Reverse Engineering',
    tags: ['rev', 'binary'],
    points: 75,
    difficulty: 'medium',
    solvesNumber: 12,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'Analyze this binary file to understand its behavior and extract the hidden flag. The flag is encrypted but the decryption routine is within the binary.',
    hints: ['Look for XOR operations', 'Check string comparisons'],
    createdAt: new Date('2024-03-05'),
    category: 'rev' as ChallengeCategory,
    assets: ['mystery_binary.exe', 'readme.txt'],
    additionalLinks: [],
    ports: [],
    dynamic: false,
  },
  {
    id: '4',
    name: 'Buffer Overflow',
    tags: ['pwn'],
    points: 100,
    difficulty: 'hard',
    solvesNumber: 5,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'This challenge involves exploiting a classic buffer overflow vulnerability in a C program. Your goal is to overflow the buffer and gain control of the program execution.',
    hints: ['Check the stack alignment', 'Try different buffer sizes'],
    createdAt: new Date('2024-01-15'),
    category: 'pwn' as ChallengeCategory,
    assets: ['buffer_overflow.c', 'vuln_binary'],
    additionalLinks: [
      'https://exploit-db.com/docs/english/28475-linux-stack-based-buffer-overflows.pdf',
    ],
    ports: [4444],
    dynamic: false,
  },
  {
    id: '5',
    name: 'SQL Injection',
    tags: ['web'],
    points: 50,
    difficulty: 'medium',
    solvesNumber: 20,
    solveStatus: 'solved',
    deployedStatus: 'deployed',
    description:
      'This web challenge contains a login form vulnerable to SQL injection. Bypass the authentication to find the flag.',
    hints: [
      'Try using single quotes in the username field',
      'UNION SELECT might be useful',
    ],
    createdAt: new Date('2024-02-10'),
    category: 'web' as ChallengeCategory,
    assets: ['login_form.php'],
    additionalLinks: [],
    ports: [8080],
    dynamic: true,
  },
  {
    id: '6',
    name: 'Reverse Engineering',
    tags: ['rev', 'binary'],
    points: 75,
    difficulty: 'medium',
    solvesNumber: 12,
    solveStatus: 'unsolved',
    deployedStatus: 'deployed',
    description:
      'Analyze this binary file to understand its behavior and extract the hidden flag. The flag is encrypted but the decryption routine is within the binary.',
    hints: ['Look for XOR operations', 'Check string comparisons'],
    createdAt: new Date('2024-03-05'),
    category: 'rev' as ChallengeCategory,
    assets: ['mystery_binary.exe', 'readme.txt'],
    additionalLinks: [],
    ports: [],
    dynamic: false,
  },
] as Challenge[];

export const MOCK_CHALLENGES_METADATA: ChallengeMetadata[] =
  MOCK_CHALLENGES.map(
    ({
      id,
      name,
      tags,
      points,
      difficulty,
      solvesNumber,
      solveStatus,
      deployedStatus,
    }) => ({
      id,
      name,
      tags,
      points,
      difficulty,
      solvesNumber,
      solveStatus,
      deployedStatus,
    })
  );
